name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Run the Docker container
      run: |
        docker run -d -p 8080:80 --name my-container-name my-image-name:$(date +%s)
      
    - name: Get container's IP address
      id: container_ip
      run: |
        container_id=$(docker ps -q --filter "name=my-container-name")
        container_ip=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $container_id)
        echo "Container IP: $container_ip"
        echo "::set-output name=ip::$container_ip"

    - name: Display the container's IP address
      run: echo "The container's IP address is ${{ steps.container_ip.outputs.ip }}"

    - name: Curl the deployed website
      run: curl http://${{ steps.container_ip.outputs.ip }}:80
